package com.yannyao.demo.mybatis_generator.mapper;

import com.yannyao.demo.mybatis_generator.domain.Wq;
import com.yannyao.demo.mybatis_generator.domain.WqExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wq
     *
     * @mbggenerated
     */
    int countByExample(WqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wq
     *
     * @mbggenerated
     */
    int deleteByExample(WqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wq
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wq
     *
     * @mbggenerated
     */
    int insert(Wq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wq
     *
     * @mbggenerated
     */
    int insertSelective(Wq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wq
     *
     * @mbggenerated
     */
    List<Wq> selectByExampleWithRowbounds(WqExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wq
     *
     * @mbggenerated
     */
    List<Wq> selectByExample(WqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wq
     *
     * @mbggenerated
     */
    Wq selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wq
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Wq record, @Param("example") WqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wq
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Wq record, @Param("example") WqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wq
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Wq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wq
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Wq record);
}