package com.yannyao.demo.mybatis_generator.mapper;

import com.yannyao.demo.mybatis_generator.domain.YmOrder;
import com.yannyao.demo.mybatis_generator.domain.YmOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface YmOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ym_order
     *
     * @mbggenerated
     */
    int countByExample(YmOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ym_order
     *
     * @mbggenerated
     */
    int deleteByExample(YmOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ym_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ym_order
     *
     * @mbggenerated
     */
    int insert(YmOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ym_order
     *
     * @mbggenerated
     */
    int insertSelective(YmOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ym_order
     *
     * @mbggenerated
     */
    List<YmOrder> selectByExampleWithBLOBsWithRowbounds(YmOrderExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ym_order
     *
     * @mbggenerated
     */
    List<YmOrder> selectByExampleWithBLOBs(YmOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ym_order
     *
     * @mbggenerated
     */
    List<YmOrder> selectByExampleWithRowbounds(YmOrderExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ym_order
     *
     * @mbggenerated
     */
    List<YmOrder> selectByExample(YmOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ym_order
     *
     * @mbggenerated
     */
    YmOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ym_order
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") YmOrder record, @Param("example") YmOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ym_order
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") YmOrder record, @Param("example") YmOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ym_order
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") YmOrder record, @Param("example") YmOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ym_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(YmOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ym_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(YmOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ym_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(YmOrder record);
}