spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/test_springboot?useSSL=false
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: yimo0011
mybatis-plus:
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
server:
  port: 8085