package com.yannyao.demo.mybatis_generator.domain;

import java.math.BigDecimal;
import java.util.Date;

public class Wq {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wq.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wq.orderSkuId
     *
     * @mbggenerated
     */
    private Long orderSkuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wq.orderId
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wq.wqStatus
     *
     * @mbggenerated
     */
    private Integer wqStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wq.refundAmout
     *
     * @mbggenerated
     */
    private BigDecimal refundAmout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wq.sellerIsAgree
     *
     * @mbggenerated
     */
    private Boolean sellerIsAgree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wq.handlerAt
     *
     * @mbggenerated
     */
    private Date handlerAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wq.imgs
     *
     * @mbggenerated
     */
    private String imgs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wq.note
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wq.reason
     *
     * @mbggenerated
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wq.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wq.tel
     *
     * @mbggenerated
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wq.appId
     *
     * @mbggenerated
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wq.createAt
     *
     * @mbggenerated
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wq.sellerReason
     *
     * @mbggenerated
     */
    private String sellerReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wq.prepayId
     *
     * @mbggenerated
     */
    private String prepayId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wq.id
     *
     * @return the value of wq.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wq.id
     *
     * @param id the value for wq.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wq.orderSkuId
     *
     * @return the value of wq.orderSkuId
     *
     * @mbggenerated
     */
    public Long getOrderSkuId() {
        return orderSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wq.orderSkuId
     *
     * @param orderSkuId the value for wq.orderSkuId
     *
     * @mbggenerated
     */
    public void setOrderSkuId(Long orderSkuId) {
        this.orderSkuId = orderSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wq.orderId
     *
     * @return the value of wq.orderId
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wq.orderId
     *
     * @param orderId the value for wq.orderId
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wq.wqStatus
     *
     * @return the value of wq.wqStatus
     *
     * @mbggenerated
     */
    public Integer getWqStatus() {
        return wqStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wq.wqStatus
     *
     * @param wqStatus the value for wq.wqStatus
     *
     * @mbggenerated
     */
    public void setWqStatus(Integer wqStatus) {
        this.wqStatus = wqStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wq.refundAmout
     *
     * @return the value of wq.refundAmout
     *
     * @mbggenerated
     */
    public BigDecimal getRefundAmout() {
        return refundAmout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wq.refundAmout
     *
     * @param refundAmout the value for wq.refundAmout
     *
     * @mbggenerated
     */
    public void setRefundAmout(BigDecimal refundAmout) {
        this.refundAmout = refundAmout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wq.sellerIsAgree
     *
     * @return the value of wq.sellerIsAgree
     *
     * @mbggenerated
     */
    public Boolean getSellerIsAgree() {
        return sellerIsAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wq.sellerIsAgree
     *
     * @param sellerIsAgree the value for wq.sellerIsAgree
     *
     * @mbggenerated
     */
    public void setSellerIsAgree(Boolean sellerIsAgree) {
        this.sellerIsAgree = sellerIsAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wq.handlerAt
     *
     * @return the value of wq.handlerAt
     *
     * @mbggenerated
     */
    public Date getHandlerAt() {
        return handlerAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wq.handlerAt
     *
     * @param handlerAt the value for wq.handlerAt
     *
     * @mbggenerated
     */
    public void setHandlerAt(Date handlerAt) {
        this.handlerAt = handlerAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wq.imgs
     *
     * @return the value of wq.imgs
     *
     * @mbggenerated
     */
    public String getImgs() {
        return imgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wq.imgs
     *
     * @param imgs the value for wq.imgs
     *
     * @mbggenerated
     */
    public void setImgs(String imgs) {
        this.imgs = imgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wq.note
     *
     * @return the value of wq.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wq.note
     *
     * @param note the value for wq.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wq.reason
     *
     * @return the value of wq.reason
     *
     * @mbggenerated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wq.reason
     *
     * @param reason the value for wq.reason
     *
     * @mbggenerated
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wq.type
     *
     * @return the value of wq.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wq.type
     *
     * @param type the value for wq.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wq.tel
     *
     * @return the value of wq.tel
     *
     * @mbggenerated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wq.tel
     *
     * @param tel the value for wq.tel
     *
     * @mbggenerated
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wq.appId
     *
     * @return the value of wq.appId
     *
     * @mbggenerated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wq.appId
     *
     * @param appId the value for wq.appId
     *
     * @mbggenerated
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wq.createAt
     *
     * @return the value of wq.createAt
     *
     * @mbggenerated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wq.createAt
     *
     * @param createAt the value for wq.createAt
     *
     * @mbggenerated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wq.sellerReason
     *
     * @return the value of wq.sellerReason
     *
     * @mbggenerated
     */
    public String getSellerReason() {
        return sellerReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wq.sellerReason
     *
     * @param sellerReason the value for wq.sellerReason
     *
     * @mbggenerated
     */
    public void setSellerReason(String sellerReason) {
        this.sellerReason = sellerReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wq.prepayId
     *
     * @return the value of wq.prepayId
     *
     * @mbggenerated
     */
    public String getPrepayId() {
        return prepayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wq.prepayId
     *
     * @param prepayId the value for wq.prepayId
     *
     * @mbggenerated
     */
    public void setPrepayId(String prepayId) {
        this.prepayId = prepayId;
    }
}