package com.yannyao.demo.mybatis_generator.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WqExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wq
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wq
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wq
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wq
     *
     * @mbggenerated
     */
    public WqExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wq
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wq
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wq
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wq
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wq
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wq
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wq
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wq
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wq
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wq
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wq
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrderSkuIdIsNull() {
            addCriterion("orderSkuId is null");
            return (Criteria) this;
        }

        public Criteria andOrderSkuIdIsNotNull() {
            addCriterion("orderSkuId is not null");
            return (Criteria) this;
        }

        public Criteria andOrderSkuIdEqualTo(Long value) {
            addCriterion("orderSkuId =", value, "orderSkuId");
            return (Criteria) this;
        }

        public Criteria andOrderSkuIdNotEqualTo(Long value) {
            addCriterion("orderSkuId <>", value, "orderSkuId");
            return (Criteria) this;
        }

        public Criteria andOrderSkuIdGreaterThan(Long value) {
            addCriterion("orderSkuId >", value, "orderSkuId");
            return (Criteria) this;
        }

        public Criteria andOrderSkuIdGreaterThanOrEqualTo(Long value) {
            addCriterion("orderSkuId >=", value, "orderSkuId");
            return (Criteria) this;
        }

        public Criteria andOrderSkuIdLessThan(Long value) {
            addCriterion("orderSkuId <", value, "orderSkuId");
            return (Criteria) this;
        }

        public Criteria andOrderSkuIdLessThanOrEqualTo(Long value) {
            addCriterion("orderSkuId <=", value, "orderSkuId");
            return (Criteria) this;
        }

        public Criteria andOrderSkuIdIn(List<Long> values) {
            addCriterion("orderSkuId in", values, "orderSkuId");
            return (Criteria) this;
        }

        public Criteria andOrderSkuIdNotIn(List<Long> values) {
            addCriterion("orderSkuId not in", values, "orderSkuId");
            return (Criteria) this;
        }

        public Criteria andOrderSkuIdBetween(Long value1, Long value2) {
            addCriterion("orderSkuId between", value1, value2, "orderSkuId");
            return (Criteria) this;
        }

        public Criteria andOrderSkuIdNotBetween(Long value1, Long value2) {
            addCriterion("orderSkuId not between", value1, value2, "orderSkuId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("orderId is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("orderId is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(Long value) {
            addCriterion("orderId =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(Long value) {
            addCriterion("orderId <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(Long value) {
            addCriterion("orderId >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(Long value) {
            addCriterion("orderId >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(Long value) {
            addCriterion("orderId <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(Long value) {
            addCriterion("orderId <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<Long> values) {
            addCriterion("orderId in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<Long> values) {
            addCriterion("orderId not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(Long value1, Long value2) {
            addCriterion("orderId between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(Long value1, Long value2) {
            addCriterion("orderId not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andWqStatusIsNull() {
            addCriterion("wqStatus is null");
            return (Criteria) this;
        }

        public Criteria andWqStatusIsNotNull() {
            addCriterion("wqStatus is not null");
            return (Criteria) this;
        }

        public Criteria andWqStatusEqualTo(Integer value) {
            addCriterion("wqStatus =", value, "wqStatus");
            return (Criteria) this;
        }

        public Criteria andWqStatusNotEqualTo(Integer value) {
            addCriterion("wqStatus <>", value, "wqStatus");
            return (Criteria) this;
        }

        public Criteria andWqStatusGreaterThan(Integer value) {
            addCriterion("wqStatus >", value, "wqStatus");
            return (Criteria) this;
        }

        public Criteria andWqStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("wqStatus >=", value, "wqStatus");
            return (Criteria) this;
        }

        public Criteria andWqStatusLessThan(Integer value) {
            addCriterion("wqStatus <", value, "wqStatus");
            return (Criteria) this;
        }

        public Criteria andWqStatusLessThanOrEqualTo(Integer value) {
            addCriterion("wqStatus <=", value, "wqStatus");
            return (Criteria) this;
        }

        public Criteria andWqStatusIn(List<Integer> values) {
            addCriterion("wqStatus in", values, "wqStatus");
            return (Criteria) this;
        }

        public Criteria andWqStatusNotIn(List<Integer> values) {
            addCriterion("wqStatus not in", values, "wqStatus");
            return (Criteria) this;
        }

        public Criteria andWqStatusBetween(Integer value1, Integer value2) {
            addCriterion("wqStatus between", value1, value2, "wqStatus");
            return (Criteria) this;
        }

        public Criteria andWqStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("wqStatus not between", value1, value2, "wqStatus");
            return (Criteria) this;
        }

        public Criteria andRefundAmoutIsNull() {
            addCriterion("refundAmout is null");
            return (Criteria) this;
        }

        public Criteria andRefundAmoutIsNotNull() {
            addCriterion("refundAmout is not null");
            return (Criteria) this;
        }

        public Criteria andRefundAmoutEqualTo(BigDecimal value) {
            addCriterion("refundAmout =", value, "refundAmout");
            return (Criteria) this;
        }

        public Criteria andRefundAmoutNotEqualTo(BigDecimal value) {
            addCriterion("refundAmout <>", value, "refundAmout");
            return (Criteria) this;
        }

        public Criteria andRefundAmoutGreaterThan(BigDecimal value) {
            addCriterion("refundAmout >", value, "refundAmout");
            return (Criteria) this;
        }

        public Criteria andRefundAmoutGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("refundAmout >=", value, "refundAmout");
            return (Criteria) this;
        }

        public Criteria andRefundAmoutLessThan(BigDecimal value) {
            addCriterion("refundAmout <", value, "refundAmout");
            return (Criteria) this;
        }

        public Criteria andRefundAmoutLessThanOrEqualTo(BigDecimal value) {
            addCriterion("refundAmout <=", value, "refundAmout");
            return (Criteria) this;
        }

        public Criteria andRefundAmoutIn(List<BigDecimal> values) {
            addCriterion("refundAmout in", values, "refundAmout");
            return (Criteria) this;
        }

        public Criteria andRefundAmoutNotIn(List<BigDecimal> values) {
            addCriterion("refundAmout not in", values, "refundAmout");
            return (Criteria) this;
        }

        public Criteria andRefundAmoutBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("refundAmout between", value1, value2, "refundAmout");
            return (Criteria) this;
        }

        public Criteria andRefundAmoutNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("refundAmout not between", value1, value2, "refundAmout");
            return (Criteria) this;
        }

        public Criteria andSellerIsAgreeIsNull() {
            addCriterion("sellerIsAgree is null");
            return (Criteria) this;
        }

        public Criteria andSellerIsAgreeIsNotNull() {
            addCriterion("sellerIsAgree is not null");
            return (Criteria) this;
        }

        public Criteria andSellerIsAgreeEqualTo(Boolean value) {
            addCriterion("sellerIsAgree =", value, "sellerIsAgree");
            return (Criteria) this;
        }

        public Criteria andSellerIsAgreeNotEqualTo(Boolean value) {
            addCriterion("sellerIsAgree <>", value, "sellerIsAgree");
            return (Criteria) this;
        }

        public Criteria andSellerIsAgreeGreaterThan(Boolean value) {
            addCriterion("sellerIsAgree >", value, "sellerIsAgree");
            return (Criteria) this;
        }

        public Criteria andSellerIsAgreeGreaterThanOrEqualTo(Boolean value) {
            addCriterion("sellerIsAgree >=", value, "sellerIsAgree");
            return (Criteria) this;
        }

        public Criteria andSellerIsAgreeLessThan(Boolean value) {
            addCriterion("sellerIsAgree <", value, "sellerIsAgree");
            return (Criteria) this;
        }

        public Criteria andSellerIsAgreeLessThanOrEqualTo(Boolean value) {
            addCriterion("sellerIsAgree <=", value, "sellerIsAgree");
            return (Criteria) this;
        }

        public Criteria andSellerIsAgreeIn(List<Boolean> values) {
            addCriterion("sellerIsAgree in", values, "sellerIsAgree");
            return (Criteria) this;
        }

        public Criteria andSellerIsAgreeNotIn(List<Boolean> values) {
            addCriterion("sellerIsAgree not in", values, "sellerIsAgree");
            return (Criteria) this;
        }

        public Criteria andSellerIsAgreeBetween(Boolean value1, Boolean value2) {
            addCriterion("sellerIsAgree between", value1, value2, "sellerIsAgree");
            return (Criteria) this;
        }

        public Criteria andSellerIsAgreeNotBetween(Boolean value1, Boolean value2) {
            addCriterion("sellerIsAgree not between", value1, value2, "sellerIsAgree");
            return (Criteria) this;
        }

        public Criteria andHandlerAtIsNull() {
            addCriterion("handlerAt is null");
            return (Criteria) this;
        }

        public Criteria andHandlerAtIsNotNull() {
            addCriterion("handlerAt is not null");
            return (Criteria) this;
        }

        public Criteria andHandlerAtEqualTo(Date value) {
            addCriterion("handlerAt =", value, "handlerAt");
            return (Criteria) this;
        }

        public Criteria andHandlerAtNotEqualTo(Date value) {
            addCriterion("handlerAt <>", value, "handlerAt");
            return (Criteria) this;
        }

        public Criteria andHandlerAtGreaterThan(Date value) {
            addCriterion("handlerAt >", value, "handlerAt");
            return (Criteria) this;
        }

        public Criteria andHandlerAtGreaterThanOrEqualTo(Date value) {
            addCriterion("handlerAt >=", value, "handlerAt");
            return (Criteria) this;
        }

        public Criteria andHandlerAtLessThan(Date value) {
            addCriterion("handlerAt <", value, "handlerAt");
            return (Criteria) this;
        }

        public Criteria andHandlerAtLessThanOrEqualTo(Date value) {
            addCriterion("handlerAt <=", value, "handlerAt");
            return (Criteria) this;
        }

        public Criteria andHandlerAtIn(List<Date> values) {
            addCriterion("handlerAt in", values, "handlerAt");
            return (Criteria) this;
        }

        public Criteria andHandlerAtNotIn(List<Date> values) {
            addCriterion("handlerAt not in", values, "handlerAt");
            return (Criteria) this;
        }

        public Criteria andHandlerAtBetween(Date value1, Date value2) {
            addCriterion("handlerAt between", value1, value2, "handlerAt");
            return (Criteria) this;
        }

        public Criteria andHandlerAtNotBetween(Date value1, Date value2) {
            addCriterion("handlerAt not between", value1, value2, "handlerAt");
            return (Criteria) this;
        }

        public Criteria andImgsIsNull() {
            addCriterion("imgs is null");
            return (Criteria) this;
        }

        public Criteria andImgsIsNotNull() {
            addCriterion("imgs is not null");
            return (Criteria) this;
        }

        public Criteria andImgsEqualTo(String value) {
            addCriterion("imgs =", value, "imgs");
            return (Criteria) this;
        }

        public Criteria andImgsNotEqualTo(String value) {
            addCriterion("imgs <>", value, "imgs");
            return (Criteria) this;
        }

        public Criteria andImgsGreaterThan(String value) {
            addCriterion("imgs >", value, "imgs");
            return (Criteria) this;
        }

        public Criteria andImgsGreaterThanOrEqualTo(String value) {
            addCriterion("imgs >=", value, "imgs");
            return (Criteria) this;
        }

        public Criteria andImgsLessThan(String value) {
            addCriterion("imgs <", value, "imgs");
            return (Criteria) this;
        }

        public Criteria andImgsLessThanOrEqualTo(String value) {
            addCriterion("imgs <=", value, "imgs");
            return (Criteria) this;
        }

        public Criteria andImgsLike(String value) {
            addCriterion("imgs like", value, "imgs");
            return (Criteria) this;
        }

        public Criteria andImgsNotLike(String value) {
            addCriterion("imgs not like", value, "imgs");
            return (Criteria) this;
        }

        public Criteria andImgsIn(List<String> values) {
            addCriterion("imgs in", values, "imgs");
            return (Criteria) this;
        }

        public Criteria andImgsNotIn(List<String> values) {
            addCriterion("imgs not in", values, "imgs");
            return (Criteria) this;
        }

        public Criteria andImgsBetween(String value1, String value2) {
            addCriterion("imgs between", value1, value2, "imgs");
            return (Criteria) this;
        }

        public Criteria andImgsNotBetween(String value1, String value2) {
            addCriterion("imgs not between", value1, value2, "imgs");
            return (Criteria) this;
        }

        public Criteria andNoteIsNull() {
            addCriterion("note is null");
            return (Criteria) this;
        }

        public Criteria andNoteIsNotNull() {
            addCriterion("note is not null");
            return (Criteria) this;
        }

        public Criteria andNoteEqualTo(String value) {
            addCriterion("note =", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotEqualTo(String value) {
            addCriterion("note <>", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThan(String value) {
            addCriterion("note >", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThanOrEqualTo(String value) {
            addCriterion("note >=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThan(String value) {
            addCriterion("note <", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThanOrEqualTo(String value) {
            addCriterion("note <=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLike(String value) {
            addCriterion("note like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotLike(String value) {
            addCriterion("note not like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteIn(List<String> values) {
            addCriterion("note in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotIn(List<String> values) {
            addCriterion("note not in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteBetween(String value1, String value2) {
            addCriterion("note between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotBetween(String value1, String value2) {
            addCriterion("note not between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andReasonIsNull() {
            addCriterion("reason is null");
            return (Criteria) this;
        }

        public Criteria andReasonIsNotNull() {
            addCriterion("reason is not null");
            return (Criteria) this;
        }

        public Criteria andReasonEqualTo(String value) {
            addCriterion("reason =", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotEqualTo(String value) {
            addCriterion("reason <>", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonGreaterThan(String value) {
            addCriterion("reason >", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonGreaterThanOrEqualTo(String value) {
            addCriterion("reason >=", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonLessThan(String value) {
            addCriterion("reason <", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonLessThanOrEqualTo(String value) {
            addCriterion("reason <=", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonLike(String value) {
            addCriterion("reason like", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotLike(String value) {
            addCriterion("reason not like", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonIn(List<String> values) {
            addCriterion("reason in", values, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotIn(List<String> values) {
            addCriterion("reason not in", values, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonBetween(String value1, String value2) {
            addCriterion("reason between", value1, value2, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotBetween(String value1, String value2) {
            addCriterion("reason not between", value1, value2, "reason");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTelIsNull() {
            addCriterion("tel is null");
            return (Criteria) this;
        }

        public Criteria andTelIsNotNull() {
            addCriterion("tel is not null");
            return (Criteria) this;
        }

        public Criteria andTelEqualTo(String value) {
            addCriterion("tel =", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotEqualTo(String value) {
            addCriterion("tel <>", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThan(String value) {
            addCriterion("tel >", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThanOrEqualTo(String value) {
            addCriterion("tel >=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThan(String value) {
            addCriterion("tel <", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThanOrEqualTo(String value) {
            addCriterion("tel <=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLike(String value) {
            addCriterion("tel like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotLike(String value) {
            addCriterion("tel not like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelIn(List<String> values) {
            addCriterion("tel in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotIn(List<String> values) {
            addCriterion("tel not in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelBetween(String value1, String value2) {
            addCriterion("tel between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotBetween(String value1, String value2) {
            addCriterion("tel not between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNull() {
            addCriterion("appId is null");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNotNull() {
            addCriterion("appId is not null");
            return (Criteria) this;
        }

        public Criteria andAppIdEqualTo(String value) {
            addCriterion("appId =", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotEqualTo(String value) {
            addCriterion("appId <>", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThan(String value) {
            addCriterion("appId >", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThanOrEqualTo(String value) {
            addCriterion("appId >=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThan(String value) {
            addCriterion("appId <", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThanOrEqualTo(String value) {
            addCriterion("appId <=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLike(String value) {
            addCriterion("appId like", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotLike(String value) {
            addCriterion("appId not like", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdIn(List<String> values) {
            addCriterion("appId in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotIn(List<String> values) {
            addCriterion("appId not in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdBetween(String value1, String value2) {
            addCriterion("appId between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotBetween(String value1, String value2) {
            addCriterion("appId not between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andCreateAtIsNull() {
            addCriterion("createAt is null");
            return (Criteria) this;
        }

        public Criteria andCreateAtIsNotNull() {
            addCriterion("createAt is not null");
            return (Criteria) this;
        }

        public Criteria andCreateAtEqualTo(Date value) {
            addCriterion("createAt =", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotEqualTo(Date value) {
            addCriterion("createAt <>", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtGreaterThan(Date value) {
            addCriterion("createAt >", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtGreaterThanOrEqualTo(Date value) {
            addCriterion("createAt >=", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtLessThan(Date value) {
            addCriterion("createAt <", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtLessThanOrEqualTo(Date value) {
            addCriterion("createAt <=", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtIn(List<Date> values) {
            addCriterion("createAt in", values, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotIn(List<Date> values) {
            addCriterion("createAt not in", values, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtBetween(Date value1, Date value2) {
            addCriterion("createAt between", value1, value2, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotBetween(Date value1, Date value2) {
            addCriterion("createAt not between", value1, value2, "createAt");
            return (Criteria) this;
        }

        public Criteria andSellerReasonIsNull() {
            addCriterion("sellerReason is null");
            return (Criteria) this;
        }

        public Criteria andSellerReasonIsNotNull() {
            addCriterion("sellerReason is not null");
            return (Criteria) this;
        }

        public Criteria andSellerReasonEqualTo(String value) {
            addCriterion("sellerReason =", value, "sellerReason");
            return (Criteria) this;
        }

        public Criteria andSellerReasonNotEqualTo(String value) {
            addCriterion("sellerReason <>", value, "sellerReason");
            return (Criteria) this;
        }

        public Criteria andSellerReasonGreaterThan(String value) {
            addCriterion("sellerReason >", value, "sellerReason");
            return (Criteria) this;
        }

        public Criteria andSellerReasonGreaterThanOrEqualTo(String value) {
            addCriterion("sellerReason >=", value, "sellerReason");
            return (Criteria) this;
        }

        public Criteria andSellerReasonLessThan(String value) {
            addCriterion("sellerReason <", value, "sellerReason");
            return (Criteria) this;
        }

        public Criteria andSellerReasonLessThanOrEqualTo(String value) {
            addCriterion("sellerReason <=", value, "sellerReason");
            return (Criteria) this;
        }

        public Criteria andSellerReasonLike(String value) {
            addCriterion("sellerReason like", value, "sellerReason");
            return (Criteria) this;
        }

        public Criteria andSellerReasonNotLike(String value) {
            addCriterion("sellerReason not like", value, "sellerReason");
            return (Criteria) this;
        }

        public Criteria andSellerReasonIn(List<String> values) {
            addCriterion("sellerReason in", values, "sellerReason");
            return (Criteria) this;
        }

        public Criteria andSellerReasonNotIn(List<String> values) {
            addCriterion("sellerReason not in", values, "sellerReason");
            return (Criteria) this;
        }

        public Criteria andSellerReasonBetween(String value1, String value2) {
            addCriterion("sellerReason between", value1, value2, "sellerReason");
            return (Criteria) this;
        }

        public Criteria andSellerReasonNotBetween(String value1, String value2) {
            addCriterion("sellerReason not between", value1, value2, "sellerReason");
            return (Criteria) this;
        }

        public Criteria andPrepayIdIsNull() {
            addCriterion("prepayId is null");
            return (Criteria) this;
        }

        public Criteria andPrepayIdIsNotNull() {
            addCriterion("prepayId is not null");
            return (Criteria) this;
        }

        public Criteria andPrepayIdEqualTo(String value) {
            addCriterion("prepayId =", value, "prepayId");
            return (Criteria) this;
        }

        public Criteria andPrepayIdNotEqualTo(String value) {
            addCriterion("prepayId <>", value, "prepayId");
            return (Criteria) this;
        }

        public Criteria andPrepayIdGreaterThan(String value) {
            addCriterion("prepayId >", value, "prepayId");
            return (Criteria) this;
        }

        public Criteria andPrepayIdGreaterThanOrEqualTo(String value) {
            addCriterion("prepayId >=", value, "prepayId");
            return (Criteria) this;
        }

        public Criteria andPrepayIdLessThan(String value) {
            addCriterion("prepayId <", value, "prepayId");
            return (Criteria) this;
        }

        public Criteria andPrepayIdLessThanOrEqualTo(String value) {
            addCriterion("prepayId <=", value, "prepayId");
            return (Criteria) this;
        }

        public Criteria andPrepayIdLike(String value) {
            addCriterion("prepayId like", value, "prepayId");
            return (Criteria) this;
        }

        public Criteria andPrepayIdNotLike(String value) {
            addCriterion("prepayId not like", value, "prepayId");
            return (Criteria) this;
        }

        public Criteria andPrepayIdIn(List<String> values) {
            addCriterion("prepayId in", values, "prepayId");
            return (Criteria) this;
        }

        public Criteria andPrepayIdNotIn(List<String> values) {
            addCriterion("prepayId not in", values, "prepayId");
            return (Criteria) this;
        }

        public Criteria andPrepayIdBetween(String value1, String value2) {
            addCriterion("prepayId between", value1, value2, "prepayId");
            return (Criteria) this;
        }

        public Criteria andPrepayIdNotBetween(String value1, String value2) {
            addCriterion("prepayId not between", value1, value2, "prepayId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wq
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wq
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}