package com.yannyao.demo.mybatis_generator.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class YmOrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ym_order
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ym_order
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ym_order
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ym_order
     *
     * @mbggenerated
     */
    public YmOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ym_order
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ym_order
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ym_order
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ym_order
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ym_order
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ym_order
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ym_order
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ym_order
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ym_order
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ym_order
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ym_order
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTidIsNull() {
            addCriterion("tid is null");
            return (Criteria) this;
        }

        public Criteria andTidIsNotNull() {
            addCriterion("tid is not null");
            return (Criteria) this;
        }

        public Criteria andTidEqualTo(Long value) {
            addCriterion("tid =", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidNotEqualTo(Long value) {
            addCriterion("tid <>", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidGreaterThan(Long value) {
            addCriterion("tid >", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidGreaterThanOrEqualTo(Long value) {
            addCriterion("tid >=", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidLessThan(Long value) {
            addCriterion("tid <", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidLessThanOrEqualTo(Long value) {
            addCriterion("tid <=", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidIn(List<Long> values) {
            addCriterion("tid in", values, "tid");
            return (Criteria) this;
        }

        public Criteria andTidNotIn(List<Long> values) {
            addCriterion("tid not in", values, "tid");
            return (Criteria) this;
        }

        public Criteria andTidBetween(Long value1, Long value2) {
            addCriterion("tid between", value1, value2, "tid");
            return (Criteria) this;
        }

        public Criteria andTidNotBetween(Long value1, Long value2) {
            addCriterion("tid not between", value1, value2, "tid");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("userId is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("userId is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("userId =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("userId <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("userId >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("userId >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("userId <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("userId <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("userId in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("userId not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("userId between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("userId not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andAddressIdIsNull() {
            addCriterion("addressId is null");
            return (Criteria) this;
        }

        public Criteria andAddressIdIsNotNull() {
            addCriterion("addressId is not null");
            return (Criteria) this;
        }

        public Criteria andAddressIdEqualTo(Long value) {
            addCriterion("addressId =", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdNotEqualTo(Long value) {
            addCriterion("addressId <>", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdGreaterThan(Long value) {
            addCriterion("addressId >", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdGreaterThanOrEqualTo(Long value) {
            addCriterion("addressId >=", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdLessThan(Long value) {
            addCriterion("addressId <", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdLessThanOrEqualTo(Long value) {
            addCriterion("addressId <=", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdIn(List<Long> values) {
            addCriterion("addressId in", values, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdNotIn(List<Long> values) {
            addCriterion("addressId not in", values, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdBetween(Long value1, Long value2) {
            addCriterion("addressId between", value1, value2, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdNotBetween(Long value1, Long value2) {
            addCriterion("addressId not between", value1, value2, "addressId");
            return (Criteria) this;
        }

        public Criteria andShopIdIsNull() {
            addCriterion("shopId is null");
            return (Criteria) this;
        }

        public Criteria andShopIdIsNotNull() {
            addCriterion("shopId is not null");
            return (Criteria) this;
        }

        public Criteria andShopIdEqualTo(Long value) {
            addCriterion("shopId =", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotEqualTo(Long value) {
            addCriterion("shopId <>", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdGreaterThan(Long value) {
            addCriterion("shopId >", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdGreaterThanOrEqualTo(Long value) {
            addCriterion("shopId >=", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdLessThan(Long value) {
            addCriterion("shopId <", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdLessThanOrEqualTo(Long value) {
            addCriterion("shopId <=", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdIn(List<Long> values) {
            addCriterion("shopId in", values, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotIn(List<Long> values) {
            addCriterion("shopId not in", values, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdBetween(Long value1, Long value2) {
            addCriterion("shopId between", value1, value2, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotBetween(Long value1, Long value2) {
            addCriterion("shopId not between", value1, value2, "shopId");
            return (Criteria) this;
        }

        public Criteria andActivityTypeIsNull() {
            addCriterion("activityType is null");
            return (Criteria) this;
        }

        public Criteria andActivityTypeIsNotNull() {
            addCriterion("activityType is not null");
            return (Criteria) this;
        }

        public Criteria andActivityTypeEqualTo(Integer value) {
            addCriterion("activityType =", value, "activityType");
            return (Criteria) this;
        }

        public Criteria andActivityTypeNotEqualTo(Integer value) {
            addCriterion("activityType <>", value, "activityType");
            return (Criteria) this;
        }

        public Criteria andActivityTypeGreaterThan(Integer value) {
            addCriterion("activityType >", value, "activityType");
            return (Criteria) this;
        }

        public Criteria andActivityTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("activityType >=", value, "activityType");
            return (Criteria) this;
        }

        public Criteria andActivityTypeLessThan(Integer value) {
            addCriterion("activityType <", value, "activityType");
            return (Criteria) this;
        }

        public Criteria andActivityTypeLessThanOrEqualTo(Integer value) {
            addCriterion("activityType <=", value, "activityType");
            return (Criteria) this;
        }

        public Criteria andActivityTypeIn(List<Integer> values) {
            addCriterion("activityType in", values, "activityType");
            return (Criteria) this;
        }

        public Criteria andActivityTypeNotIn(List<Integer> values) {
            addCriterion("activityType not in", values, "activityType");
            return (Criteria) this;
        }

        public Criteria andActivityTypeBetween(Integer value1, Integer value2) {
            addCriterion("activityType between", value1, value2, "activityType");
            return (Criteria) this;
        }

        public Criteria andActivityTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("activityType not between", value1, value2, "activityType");
            return (Criteria) this;
        }

        public Criteria andActivityIdIsNull() {
            addCriterion("activityId is null");
            return (Criteria) this;
        }

        public Criteria andActivityIdIsNotNull() {
            addCriterion("activityId is not null");
            return (Criteria) this;
        }

        public Criteria andActivityIdEqualTo(Long value) {
            addCriterion("activityId =", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdNotEqualTo(Long value) {
            addCriterion("activityId <>", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdGreaterThan(Long value) {
            addCriterion("activityId >", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdGreaterThanOrEqualTo(Long value) {
            addCriterion("activityId >=", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdLessThan(Long value) {
            addCriterion("activityId <", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdLessThanOrEqualTo(Long value) {
            addCriterion("activityId <=", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdIn(List<Long> values) {
            addCriterion("activityId in", values, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdNotIn(List<Long> values) {
            addCriterion("activityId not in", values, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdBetween(Long value1, Long value2) {
            addCriterion("activityId between", value1, value2, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdNotBetween(Long value1, Long value2) {
            addCriterion("activityId not between", value1, value2, "activityId");
            return (Criteria) this;
        }

        public Criteria andPaymentRecordIdIsNull() {
            addCriterion("paymentRecordId is null");
            return (Criteria) this;
        }

        public Criteria andPaymentRecordIdIsNotNull() {
            addCriterion("paymentRecordId is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentRecordIdEqualTo(Long value) {
            addCriterion("paymentRecordId =", value, "paymentRecordId");
            return (Criteria) this;
        }

        public Criteria andPaymentRecordIdNotEqualTo(Long value) {
            addCriterion("paymentRecordId <>", value, "paymentRecordId");
            return (Criteria) this;
        }

        public Criteria andPaymentRecordIdGreaterThan(Long value) {
            addCriterion("paymentRecordId >", value, "paymentRecordId");
            return (Criteria) this;
        }

        public Criteria andPaymentRecordIdGreaterThanOrEqualTo(Long value) {
            addCriterion("paymentRecordId >=", value, "paymentRecordId");
            return (Criteria) this;
        }

        public Criteria andPaymentRecordIdLessThan(Long value) {
            addCriterion("paymentRecordId <", value, "paymentRecordId");
            return (Criteria) this;
        }

        public Criteria andPaymentRecordIdLessThanOrEqualTo(Long value) {
            addCriterion("paymentRecordId <=", value, "paymentRecordId");
            return (Criteria) this;
        }

        public Criteria andPaymentRecordIdIn(List<Long> values) {
            addCriterion("paymentRecordId in", values, "paymentRecordId");
            return (Criteria) this;
        }

        public Criteria andPaymentRecordIdNotIn(List<Long> values) {
            addCriterion("paymentRecordId not in", values, "paymentRecordId");
            return (Criteria) this;
        }

        public Criteria andPaymentRecordIdBetween(Long value1, Long value2) {
            addCriterion("paymentRecordId between", value1, value2, "paymentRecordId");
            return (Criteria) this;
        }

        public Criteria andPaymentRecordIdNotBetween(Long value1, Long value2) {
            addCriterion("paymentRecordId not between", value1, value2, "paymentRecordId");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNull() {
            addCriterion("orderNo is null");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNotNull() {
            addCriterion("orderNo is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNoEqualTo(Long value) {
            addCriterion("orderNo =", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotEqualTo(Long value) {
            addCriterion("orderNo <>", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThan(Long value) {
            addCriterion("orderNo >", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThanOrEqualTo(Long value) {
            addCriterion("orderNo >=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThan(Long value) {
            addCriterion("orderNo <", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThanOrEqualTo(Long value) {
            addCriterion("orderNo <=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoIn(List<Long> values) {
            addCriterion("orderNo in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotIn(List<Long> values) {
            addCriterion("orderNo not in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoBetween(Long value1, Long value2) {
            addCriterion("orderNo between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotBetween(Long value1, Long value2) {
            addCriterion("orderNo not between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andShipNoIsNull() {
            addCriterion("shipNo is null");
            return (Criteria) this;
        }

        public Criteria andShipNoIsNotNull() {
            addCriterion("shipNo is not null");
            return (Criteria) this;
        }

        public Criteria andShipNoEqualTo(String value) {
            addCriterion("shipNo =", value, "shipNo");
            return (Criteria) this;
        }

        public Criteria andShipNoNotEqualTo(String value) {
            addCriterion("shipNo <>", value, "shipNo");
            return (Criteria) this;
        }

        public Criteria andShipNoGreaterThan(String value) {
            addCriterion("shipNo >", value, "shipNo");
            return (Criteria) this;
        }

        public Criteria andShipNoGreaterThanOrEqualTo(String value) {
            addCriterion("shipNo >=", value, "shipNo");
            return (Criteria) this;
        }

        public Criteria andShipNoLessThan(String value) {
            addCriterion("shipNo <", value, "shipNo");
            return (Criteria) this;
        }

        public Criteria andShipNoLessThanOrEqualTo(String value) {
            addCriterion("shipNo <=", value, "shipNo");
            return (Criteria) this;
        }

        public Criteria andShipNoLike(String value) {
            addCriterion("shipNo like", value, "shipNo");
            return (Criteria) this;
        }

        public Criteria andShipNoNotLike(String value) {
            addCriterion("shipNo not like", value, "shipNo");
            return (Criteria) this;
        }

        public Criteria andShipNoIn(List<String> values) {
            addCriterion("shipNo in", values, "shipNo");
            return (Criteria) this;
        }

        public Criteria andShipNoNotIn(List<String> values) {
            addCriterion("shipNo not in", values, "shipNo");
            return (Criteria) this;
        }

        public Criteria andShipNoBetween(String value1, String value2) {
            addCriterion("shipNo between", value1, value2, "shipNo");
            return (Criteria) this;
        }

        public Criteria andShipNoNotBetween(String value1, String value2) {
            addCriterion("shipNo not between", value1, value2, "shipNo");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceIsNull() {
            addCriterion("orderTotalPrice is null");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceIsNotNull() {
            addCriterion("orderTotalPrice is not null");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceEqualTo(BigDecimal value) {
            addCriterion("orderTotalPrice =", value, "orderTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceNotEqualTo(BigDecimal value) {
            addCriterion("orderTotalPrice <>", value, "orderTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceGreaterThan(BigDecimal value) {
            addCriterion("orderTotalPrice >", value, "orderTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("orderTotalPrice >=", value, "orderTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceLessThan(BigDecimal value) {
            addCriterion("orderTotalPrice <", value, "orderTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("orderTotalPrice <=", value, "orderTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceIn(List<BigDecimal> values) {
            addCriterion("orderTotalPrice in", values, "orderTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceNotIn(List<BigDecimal> values) {
            addCriterion("orderTotalPrice not in", values, "orderTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("orderTotalPrice between", value1, value2, "orderTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("orderTotalPrice not between", value1, value2, "orderTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderRealPriceIsNull() {
            addCriterion("orderRealPrice is null");
            return (Criteria) this;
        }

        public Criteria andOrderRealPriceIsNotNull() {
            addCriterion("orderRealPrice is not null");
            return (Criteria) this;
        }

        public Criteria andOrderRealPriceEqualTo(BigDecimal value) {
            addCriterion("orderRealPrice =", value, "orderRealPrice");
            return (Criteria) this;
        }

        public Criteria andOrderRealPriceNotEqualTo(BigDecimal value) {
            addCriterion("orderRealPrice <>", value, "orderRealPrice");
            return (Criteria) this;
        }

        public Criteria andOrderRealPriceGreaterThan(BigDecimal value) {
            addCriterion("orderRealPrice >", value, "orderRealPrice");
            return (Criteria) this;
        }

        public Criteria andOrderRealPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("orderRealPrice >=", value, "orderRealPrice");
            return (Criteria) this;
        }

        public Criteria andOrderRealPriceLessThan(BigDecimal value) {
            addCriterion("orderRealPrice <", value, "orderRealPrice");
            return (Criteria) this;
        }

        public Criteria andOrderRealPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("orderRealPrice <=", value, "orderRealPrice");
            return (Criteria) this;
        }

        public Criteria andOrderRealPriceIn(List<BigDecimal> values) {
            addCriterion("orderRealPrice in", values, "orderRealPrice");
            return (Criteria) this;
        }

        public Criteria andOrderRealPriceNotIn(List<BigDecimal> values) {
            addCriterion("orderRealPrice not in", values, "orderRealPrice");
            return (Criteria) this;
        }

        public Criteria andOrderRealPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("orderRealPrice between", value1, value2, "orderRealPrice");
            return (Criteria) this;
        }

        public Criteria andOrderRealPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("orderRealPrice not between", value1, value2, "orderRealPrice");
            return (Criteria) this;
        }

        public Criteria andActivityDiscountIsNull() {
            addCriterion("activityDiscount is null");
            return (Criteria) this;
        }

        public Criteria andActivityDiscountIsNotNull() {
            addCriterion("activityDiscount is not null");
            return (Criteria) this;
        }

        public Criteria andActivityDiscountEqualTo(BigDecimal value) {
            addCriterion("activityDiscount =", value, "activityDiscount");
            return (Criteria) this;
        }

        public Criteria andActivityDiscountNotEqualTo(BigDecimal value) {
            addCriterion("activityDiscount <>", value, "activityDiscount");
            return (Criteria) this;
        }

        public Criteria andActivityDiscountGreaterThan(BigDecimal value) {
            addCriterion("activityDiscount >", value, "activityDiscount");
            return (Criteria) this;
        }

        public Criteria andActivityDiscountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("activityDiscount >=", value, "activityDiscount");
            return (Criteria) this;
        }

        public Criteria andActivityDiscountLessThan(BigDecimal value) {
            addCriterion("activityDiscount <", value, "activityDiscount");
            return (Criteria) this;
        }

        public Criteria andActivityDiscountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("activityDiscount <=", value, "activityDiscount");
            return (Criteria) this;
        }

        public Criteria andActivityDiscountIn(List<BigDecimal> values) {
            addCriterion("activityDiscount in", values, "activityDiscount");
            return (Criteria) this;
        }

        public Criteria andActivityDiscountNotIn(List<BigDecimal> values) {
            addCriterion("activityDiscount not in", values, "activityDiscount");
            return (Criteria) this;
        }

        public Criteria andActivityDiscountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("activityDiscount between", value1, value2, "activityDiscount");
            return (Criteria) this;
        }

        public Criteria andActivityDiscountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("activityDiscount not between", value1, value2, "activityDiscount");
            return (Criteria) this;
        }

        public Criteria andCouponDiscountIsNull() {
            addCriterion("couponDiscount is null");
            return (Criteria) this;
        }

        public Criteria andCouponDiscountIsNotNull() {
            addCriterion("couponDiscount is not null");
            return (Criteria) this;
        }

        public Criteria andCouponDiscountEqualTo(BigDecimal value) {
            addCriterion("couponDiscount =", value, "couponDiscount");
            return (Criteria) this;
        }

        public Criteria andCouponDiscountNotEqualTo(BigDecimal value) {
            addCriterion("couponDiscount <>", value, "couponDiscount");
            return (Criteria) this;
        }

        public Criteria andCouponDiscountGreaterThan(BigDecimal value) {
            addCriterion("couponDiscount >", value, "couponDiscount");
            return (Criteria) this;
        }

        public Criteria andCouponDiscountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("couponDiscount >=", value, "couponDiscount");
            return (Criteria) this;
        }

        public Criteria andCouponDiscountLessThan(BigDecimal value) {
            addCriterion("couponDiscount <", value, "couponDiscount");
            return (Criteria) this;
        }

        public Criteria andCouponDiscountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("couponDiscount <=", value, "couponDiscount");
            return (Criteria) this;
        }

        public Criteria andCouponDiscountIn(List<BigDecimal> values) {
            addCriterion("couponDiscount in", values, "couponDiscount");
            return (Criteria) this;
        }

        public Criteria andCouponDiscountNotIn(List<BigDecimal> values) {
            addCriterion("couponDiscount not in", values, "couponDiscount");
            return (Criteria) this;
        }

        public Criteria andCouponDiscountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("couponDiscount between", value1, value2, "couponDiscount");
            return (Criteria) this;
        }

        public Criteria andCouponDiscountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("couponDiscount not between", value1, value2, "couponDiscount");
            return (Criteria) this;
        }

        public Criteria andFareIsNull() {
            addCriterion("fare is null");
            return (Criteria) this;
        }

        public Criteria andFareIsNotNull() {
            addCriterion("fare is not null");
            return (Criteria) this;
        }

        public Criteria andFareEqualTo(BigDecimal value) {
            addCriterion("fare =", value, "fare");
            return (Criteria) this;
        }

        public Criteria andFareNotEqualTo(BigDecimal value) {
            addCriterion("fare <>", value, "fare");
            return (Criteria) this;
        }

        public Criteria andFareGreaterThan(BigDecimal value) {
            addCriterion("fare >", value, "fare");
            return (Criteria) this;
        }

        public Criteria andFareGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("fare >=", value, "fare");
            return (Criteria) this;
        }

        public Criteria andFareLessThan(BigDecimal value) {
            addCriterion("fare <", value, "fare");
            return (Criteria) this;
        }

        public Criteria andFareLessThanOrEqualTo(BigDecimal value) {
            addCriterion("fare <=", value, "fare");
            return (Criteria) this;
        }

        public Criteria andFareIn(List<BigDecimal> values) {
            addCriterion("fare in", values, "fare");
            return (Criteria) this;
        }

        public Criteria andFareNotIn(List<BigDecimal> values) {
            addCriterion("fare not in", values, "fare");
            return (Criteria) this;
        }

        public Criteria andFareBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fare between", value1, value2, "fare");
            return (Criteria) this;
        }

        public Criteria andFareNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fare not between", value1, value2, "fare");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIsNull() {
            addCriterion("orderStatus is null");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIsNotNull() {
            addCriterion("orderStatus is not null");
            return (Criteria) this;
        }

        public Criteria andOrderStatusEqualTo(String value) {
            addCriterion("orderStatus =", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotEqualTo(String value) {
            addCriterion("orderStatus <>", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusGreaterThan(String value) {
            addCriterion("orderStatus >", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusGreaterThanOrEqualTo(String value) {
            addCriterion("orderStatus >=", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusLessThan(String value) {
            addCriterion("orderStatus <", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusLessThanOrEqualTo(String value) {
            addCriterion("orderStatus <=", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusLike(String value) {
            addCriterion("orderStatus like", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotLike(String value) {
            addCriterion("orderStatus not like", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIn(List<String> values) {
            addCriterion("orderStatus in", values, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotIn(List<String> values) {
            addCriterion("orderStatus not in", values, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusBetween(String value1, String value2) {
            addCriterion("orderStatus between", value1, value2, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotBetween(String value1, String value2) {
            addCriterion("orderStatus not between", value1, value2, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andShipStatusIsNull() {
            addCriterion("shipStatus is null");
            return (Criteria) this;
        }

        public Criteria andShipStatusIsNotNull() {
            addCriterion("shipStatus is not null");
            return (Criteria) this;
        }

        public Criteria andShipStatusEqualTo(String value) {
            addCriterion("shipStatus =", value, "shipStatus");
            return (Criteria) this;
        }

        public Criteria andShipStatusNotEqualTo(String value) {
            addCriterion("shipStatus <>", value, "shipStatus");
            return (Criteria) this;
        }

        public Criteria andShipStatusGreaterThan(String value) {
            addCriterion("shipStatus >", value, "shipStatus");
            return (Criteria) this;
        }

        public Criteria andShipStatusGreaterThanOrEqualTo(String value) {
            addCriterion("shipStatus >=", value, "shipStatus");
            return (Criteria) this;
        }

        public Criteria andShipStatusLessThan(String value) {
            addCriterion("shipStatus <", value, "shipStatus");
            return (Criteria) this;
        }

        public Criteria andShipStatusLessThanOrEqualTo(String value) {
            addCriterion("shipStatus <=", value, "shipStatus");
            return (Criteria) this;
        }

        public Criteria andShipStatusLike(String value) {
            addCriterion("shipStatus like", value, "shipStatus");
            return (Criteria) this;
        }

        public Criteria andShipStatusNotLike(String value) {
            addCriterion("shipStatus not like", value, "shipStatus");
            return (Criteria) this;
        }

        public Criteria andShipStatusIn(List<String> values) {
            addCriterion("shipStatus in", values, "shipStatus");
            return (Criteria) this;
        }

        public Criteria andShipStatusNotIn(List<String> values) {
            addCriterion("shipStatus not in", values, "shipStatus");
            return (Criteria) this;
        }

        public Criteria andShipStatusBetween(String value1, String value2) {
            addCriterion("shipStatus between", value1, value2, "shipStatus");
            return (Criteria) this;
        }

        public Criteria andShipStatusNotBetween(String value1, String value2) {
            addCriterion("shipStatus not between", value1, value2, "shipStatus");
            return (Criteria) this;
        }

        public Criteria andPayAtIsNull() {
            addCriterion("payAt is null");
            return (Criteria) this;
        }

        public Criteria andPayAtIsNotNull() {
            addCriterion("payAt is not null");
            return (Criteria) this;
        }

        public Criteria andPayAtEqualTo(Date value) {
            addCriterion("payAt =", value, "payAt");
            return (Criteria) this;
        }

        public Criteria andPayAtNotEqualTo(Date value) {
            addCriterion("payAt <>", value, "payAt");
            return (Criteria) this;
        }

        public Criteria andPayAtGreaterThan(Date value) {
            addCriterion("payAt >", value, "payAt");
            return (Criteria) this;
        }

        public Criteria andPayAtGreaterThanOrEqualTo(Date value) {
            addCriterion("payAt >=", value, "payAt");
            return (Criteria) this;
        }

        public Criteria andPayAtLessThan(Date value) {
            addCriterion("payAt <", value, "payAt");
            return (Criteria) this;
        }

        public Criteria andPayAtLessThanOrEqualTo(Date value) {
            addCriterion("payAt <=", value, "payAt");
            return (Criteria) this;
        }

        public Criteria andPayAtIn(List<Date> values) {
            addCriterion("payAt in", values, "payAt");
            return (Criteria) this;
        }

        public Criteria andPayAtNotIn(List<Date> values) {
            addCriterion("payAt not in", values, "payAt");
            return (Criteria) this;
        }

        public Criteria andPayAtBetween(Date value1, Date value2) {
            addCriterion("payAt between", value1, value2, "payAt");
            return (Criteria) this;
        }

        public Criteria andPayAtNotBetween(Date value1, Date value2) {
            addCriterion("payAt not between", value1, value2, "payAt");
            return (Criteria) this;
        }

        public Criteria andSendAtIsNull() {
            addCriterion("sendAt is null");
            return (Criteria) this;
        }

        public Criteria andSendAtIsNotNull() {
            addCriterion("sendAt is not null");
            return (Criteria) this;
        }

        public Criteria andSendAtEqualTo(Date value) {
            addCriterion("sendAt =", value, "sendAt");
            return (Criteria) this;
        }

        public Criteria andSendAtNotEqualTo(Date value) {
            addCriterion("sendAt <>", value, "sendAt");
            return (Criteria) this;
        }

        public Criteria andSendAtGreaterThan(Date value) {
            addCriterion("sendAt >", value, "sendAt");
            return (Criteria) this;
        }

        public Criteria andSendAtGreaterThanOrEqualTo(Date value) {
            addCriterion("sendAt >=", value, "sendAt");
            return (Criteria) this;
        }

        public Criteria andSendAtLessThan(Date value) {
            addCriterion("sendAt <", value, "sendAt");
            return (Criteria) this;
        }

        public Criteria andSendAtLessThanOrEqualTo(Date value) {
            addCriterion("sendAt <=", value, "sendAt");
            return (Criteria) this;
        }

        public Criteria andSendAtIn(List<Date> values) {
            addCriterion("sendAt in", values, "sendAt");
            return (Criteria) this;
        }

        public Criteria andSendAtNotIn(List<Date> values) {
            addCriterion("sendAt not in", values, "sendAt");
            return (Criteria) this;
        }

        public Criteria andSendAtBetween(Date value1, Date value2) {
            addCriterion("sendAt between", value1, value2, "sendAt");
            return (Criteria) this;
        }

        public Criteria andSendAtNotBetween(Date value1, Date value2) {
            addCriterion("sendAt not between", value1, value2, "sendAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtIsNull() {
            addCriterion("createAt is null");
            return (Criteria) this;
        }

        public Criteria andCreateAtIsNotNull() {
            addCriterion("createAt is not null");
            return (Criteria) this;
        }

        public Criteria andCreateAtEqualTo(Date value) {
            addCriterion("createAt =", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotEqualTo(Date value) {
            addCriterion("createAt <>", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtGreaterThan(Date value) {
            addCriterion("createAt >", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtGreaterThanOrEqualTo(Date value) {
            addCriterion("createAt >=", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtLessThan(Date value) {
            addCriterion("createAt <", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtLessThanOrEqualTo(Date value) {
            addCriterion("createAt <=", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtIn(List<Date> values) {
            addCriterion("createAt in", values, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotIn(List<Date> values) {
            addCriterion("createAt not in", values, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtBetween(Date value1, Date value2) {
            addCriterion("createAt between", value1, value2, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotBetween(Date value1, Date value2) {
            addCriterion("createAt not between", value1, value2, "createAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIsNull() {
            addCriterion("updateAt is null");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIsNotNull() {
            addCriterion("updateAt is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateAtEqualTo(Date value) {
            addCriterion("updateAt =", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotEqualTo(Date value) {
            addCriterion("updateAt <>", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtGreaterThan(Date value) {
            addCriterion("updateAt >", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtGreaterThanOrEqualTo(Date value) {
            addCriterion("updateAt >=", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtLessThan(Date value) {
            addCriterion("updateAt <", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtLessThanOrEqualTo(Date value) {
            addCriterion("updateAt <=", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIn(List<Date> values) {
            addCriterion("updateAt in", values, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotIn(List<Date> values) {
            addCriterion("updateAt not in", values, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtBetween(Date value1, Date value2) {
            addCriterion("updateAt between", value1, value2, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotBetween(Date value1, Date value2) {
            addCriterion("updateAt not between", value1, value2, "updateAt");
            return (Criteria) this;
        }

        public Criteria andArchiveIsNull() {
            addCriterion("archive is null");
            return (Criteria) this;
        }

        public Criteria andArchiveIsNotNull() {
            addCriterion("archive is not null");
            return (Criteria) this;
        }

        public Criteria andArchiveEqualTo(Boolean value) {
            addCriterion("archive =", value, "archive");
            return (Criteria) this;
        }

        public Criteria andArchiveNotEqualTo(Boolean value) {
            addCriterion("archive <>", value, "archive");
            return (Criteria) this;
        }

        public Criteria andArchiveGreaterThan(Boolean value) {
            addCriterion("archive >", value, "archive");
            return (Criteria) this;
        }

        public Criteria andArchiveGreaterThanOrEqualTo(Boolean value) {
            addCriterion("archive >=", value, "archive");
            return (Criteria) this;
        }

        public Criteria andArchiveLessThan(Boolean value) {
            addCriterion("archive <", value, "archive");
            return (Criteria) this;
        }

        public Criteria andArchiveLessThanOrEqualTo(Boolean value) {
            addCriterion("archive <=", value, "archive");
            return (Criteria) this;
        }

        public Criteria andArchiveIn(List<Boolean> values) {
            addCriterion("archive in", values, "archive");
            return (Criteria) this;
        }

        public Criteria andArchiveNotIn(List<Boolean> values) {
            addCriterion("archive not in", values, "archive");
            return (Criteria) this;
        }

        public Criteria andArchiveBetween(Boolean value1, Boolean value2) {
            addCriterion("archive between", value1, value2, "archive");
            return (Criteria) this;
        }

        public Criteria andArchiveNotBetween(Boolean value1, Boolean value2) {
            addCriterion("archive not between", value1, value2, "archive");
            return (Criteria) this;
        }

        public Criteria andReceiveAtIsNull() {
            addCriterion("receiveAt is null");
            return (Criteria) this;
        }

        public Criteria andReceiveAtIsNotNull() {
            addCriterion("receiveAt is not null");
            return (Criteria) this;
        }

        public Criteria andReceiveAtEqualTo(Date value) {
            addCriterion("receiveAt =", value, "receiveAt");
            return (Criteria) this;
        }

        public Criteria andReceiveAtNotEqualTo(Date value) {
            addCriterion("receiveAt <>", value, "receiveAt");
            return (Criteria) this;
        }

        public Criteria andReceiveAtGreaterThan(Date value) {
            addCriterion("receiveAt >", value, "receiveAt");
            return (Criteria) this;
        }

        public Criteria andReceiveAtGreaterThanOrEqualTo(Date value) {
            addCriterion("receiveAt >=", value, "receiveAt");
            return (Criteria) this;
        }

        public Criteria andReceiveAtLessThan(Date value) {
            addCriterion("receiveAt <", value, "receiveAt");
            return (Criteria) this;
        }

        public Criteria andReceiveAtLessThanOrEqualTo(Date value) {
            addCriterion("receiveAt <=", value, "receiveAt");
            return (Criteria) this;
        }

        public Criteria andReceiveAtIn(List<Date> values) {
            addCriterion("receiveAt in", values, "receiveAt");
            return (Criteria) this;
        }

        public Criteria andReceiveAtNotIn(List<Date> values) {
            addCriterion("receiveAt not in", values, "receiveAt");
            return (Criteria) this;
        }

        public Criteria andReceiveAtBetween(Date value1, Date value2) {
            addCriterion("receiveAt between", value1, value2, "receiveAt");
            return (Criteria) this;
        }

        public Criteria andReceiveAtNotBetween(Date value1, Date value2) {
            addCriterion("receiveAt not between", value1, value2, "receiveAt");
            return (Criteria) this;
        }

        public Criteria andExtendReceiveIsNull() {
            addCriterion("extendReceive is null");
            return (Criteria) this;
        }

        public Criteria andExtendReceiveIsNotNull() {
            addCriterion("extendReceive is not null");
            return (Criteria) this;
        }

        public Criteria andExtendReceiveEqualTo(Boolean value) {
            addCriterion("extendReceive =", value, "extendReceive");
            return (Criteria) this;
        }

        public Criteria andExtendReceiveNotEqualTo(Boolean value) {
            addCriterion("extendReceive <>", value, "extendReceive");
            return (Criteria) this;
        }

        public Criteria andExtendReceiveGreaterThan(Boolean value) {
            addCriterion("extendReceive >", value, "extendReceive");
            return (Criteria) this;
        }

        public Criteria andExtendReceiveGreaterThanOrEqualTo(Boolean value) {
            addCriterion("extendReceive >=", value, "extendReceive");
            return (Criteria) this;
        }

        public Criteria andExtendReceiveLessThan(Boolean value) {
            addCriterion("extendReceive <", value, "extendReceive");
            return (Criteria) this;
        }

        public Criteria andExtendReceiveLessThanOrEqualTo(Boolean value) {
            addCriterion("extendReceive <=", value, "extendReceive");
            return (Criteria) this;
        }

        public Criteria andExtendReceiveIn(List<Boolean> values) {
            addCriterion("extendReceive in", values, "extendReceive");
            return (Criteria) this;
        }

        public Criteria andExtendReceiveNotIn(List<Boolean> values) {
            addCriterion("extendReceive not in", values, "extendReceive");
            return (Criteria) this;
        }

        public Criteria andExtendReceiveBetween(Boolean value1, Boolean value2) {
            addCriterion("extendReceive between", value1, value2, "extendReceive");
            return (Criteria) this;
        }

        public Criteria andExtendReceiveNotBetween(Boolean value1, Boolean value2) {
            addCriterion("extendReceive not between", value1, value2, "extendReceive");
            return (Criteria) this;
        }

        public Criteria andFxIsNull() {
            addCriterion("fx is null");
            return (Criteria) this;
        }

        public Criteria andFxIsNotNull() {
            addCriterion("fx is not null");
            return (Criteria) this;
        }

        public Criteria andFxEqualTo(Boolean value) {
            addCriterion("fx =", value, "fx");
            return (Criteria) this;
        }

        public Criteria andFxNotEqualTo(Boolean value) {
            addCriterion("fx <>", value, "fx");
            return (Criteria) this;
        }

        public Criteria andFxGreaterThan(Boolean value) {
            addCriterion("fx >", value, "fx");
            return (Criteria) this;
        }

        public Criteria andFxGreaterThanOrEqualTo(Boolean value) {
            addCriterion("fx >=", value, "fx");
            return (Criteria) this;
        }

        public Criteria andFxLessThan(Boolean value) {
            addCriterion("fx <", value, "fx");
            return (Criteria) this;
        }

        public Criteria andFxLessThanOrEqualTo(Boolean value) {
            addCriterion("fx <=", value, "fx");
            return (Criteria) this;
        }

        public Criteria andFxIn(List<Boolean> values) {
            addCriterion("fx in", values, "fx");
            return (Criteria) this;
        }

        public Criteria andFxNotIn(List<Boolean> values) {
            addCriterion("fx not in", values, "fx");
            return (Criteria) this;
        }

        public Criteria andFxBetween(Boolean value1, Boolean value2) {
            addCriterion("fx between", value1, value2, "fx");
            return (Criteria) this;
        }

        public Criteria andFxNotBetween(Boolean value1, Boolean value2) {
            addCriterion("fx not between", value1, value2, "fx");
            return (Criteria) this;
        }

        public Criteria andPlatformIdIsNull() {
            addCriterion("platformId is null");
            return (Criteria) this;
        }

        public Criteria andPlatformIdIsNotNull() {
            addCriterion("platformId is not null");
            return (Criteria) this;
        }

        public Criteria andPlatformIdEqualTo(Long value) {
            addCriterion("platformId =", value, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdNotEqualTo(Long value) {
            addCriterion("platformId <>", value, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdGreaterThan(Long value) {
            addCriterion("platformId >", value, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdGreaterThanOrEqualTo(Long value) {
            addCriterion("platformId >=", value, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdLessThan(Long value) {
            addCriterion("platformId <", value, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdLessThanOrEqualTo(Long value) {
            addCriterion("platformId <=", value, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdIn(List<Long> values) {
            addCriterion("platformId in", values, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdNotIn(List<Long> values) {
            addCriterion("platformId not in", values, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdBetween(Long value1, Long value2) {
            addCriterion("platformId between", value1, value2, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdNotBetween(Long value1, Long value2) {
            addCriterion("platformId not between", value1, value2, "platformId");
            return (Criteria) this;
        }

        public Criteria andPushERPIsNull() {
            addCriterion("pushERP is null");
            return (Criteria) this;
        }

        public Criteria andPushERPIsNotNull() {
            addCriterion("pushERP is not null");
            return (Criteria) this;
        }

        public Criteria andPushERPEqualTo(Boolean value) {
            addCriterion("pushERP =", value, "pushERP");
            return (Criteria) this;
        }

        public Criteria andPushERPNotEqualTo(Boolean value) {
            addCriterion("pushERP <>", value, "pushERP");
            return (Criteria) this;
        }

        public Criteria andPushERPGreaterThan(Boolean value) {
            addCriterion("pushERP >", value, "pushERP");
            return (Criteria) this;
        }

        public Criteria andPushERPGreaterThanOrEqualTo(Boolean value) {
            addCriterion("pushERP >=", value, "pushERP");
            return (Criteria) this;
        }

        public Criteria andPushERPLessThan(Boolean value) {
            addCriterion("pushERP <", value, "pushERP");
            return (Criteria) this;
        }

        public Criteria andPushERPLessThanOrEqualTo(Boolean value) {
            addCriterion("pushERP <=", value, "pushERP");
            return (Criteria) this;
        }

        public Criteria andPushERPIn(List<Boolean> values) {
            addCriterion("pushERP in", values, "pushERP");
            return (Criteria) this;
        }

        public Criteria andPushERPNotIn(List<Boolean> values) {
            addCriterion("pushERP not in", values, "pushERP");
            return (Criteria) this;
        }

        public Criteria andPushERPBetween(Boolean value1, Boolean value2) {
            addCriterion("pushERP between", value1, value2, "pushERP");
            return (Criteria) this;
        }

        public Criteria andPushERPNotBetween(Boolean value1, Boolean value2) {
            addCriterion("pushERP not between", value1, value2, "pushERP");
            return (Criteria) this;
        }

        public Criteria andPushCancelERPIsNull() {
            addCriterion("pushCancelERP is null");
            return (Criteria) this;
        }

        public Criteria andPushCancelERPIsNotNull() {
            addCriterion("pushCancelERP is not null");
            return (Criteria) this;
        }

        public Criteria andPushCancelERPEqualTo(Boolean value) {
            addCriterion("pushCancelERP =", value, "pushCancelERP");
            return (Criteria) this;
        }

        public Criteria andPushCancelERPNotEqualTo(Boolean value) {
            addCriterion("pushCancelERP <>", value, "pushCancelERP");
            return (Criteria) this;
        }

        public Criteria andPushCancelERPGreaterThan(Boolean value) {
            addCriterion("pushCancelERP >", value, "pushCancelERP");
            return (Criteria) this;
        }

        public Criteria andPushCancelERPGreaterThanOrEqualTo(Boolean value) {
            addCriterion("pushCancelERP >=", value, "pushCancelERP");
            return (Criteria) this;
        }

        public Criteria andPushCancelERPLessThan(Boolean value) {
            addCriterion("pushCancelERP <", value, "pushCancelERP");
            return (Criteria) this;
        }

        public Criteria andPushCancelERPLessThanOrEqualTo(Boolean value) {
            addCriterion("pushCancelERP <=", value, "pushCancelERP");
            return (Criteria) this;
        }

        public Criteria andPushCancelERPIn(List<Boolean> values) {
            addCriterion("pushCancelERP in", values, "pushCancelERP");
            return (Criteria) this;
        }

        public Criteria andPushCancelERPNotIn(List<Boolean> values) {
            addCriterion("pushCancelERP not in", values, "pushCancelERP");
            return (Criteria) this;
        }

        public Criteria andPushCancelERPBetween(Boolean value1, Boolean value2) {
            addCriterion("pushCancelERP between", value1, value2, "pushCancelERP");
            return (Criteria) this;
        }

        public Criteria andPushCancelERPNotBetween(Boolean value1, Boolean value2) {
            addCriterion("pushCancelERP not between", value1, value2, "pushCancelERP");
            return (Criteria) this;
        }

        public Criteria andLastSyncAtIsNull() {
            addCriterion("lastSyncAt is null");
            return (Criteria) this;
        }

        public Criteria andLastSyncAtIsNotNull() {
            addCriterion("lastSyncAt is not null");
            return (Criteria) this;
        }

        public Criteria andLastSyncAtEqualTo(Date value) {
            addCriterion("lastSyncAt =", value, "lastSyncAt");
            return (Criteria) this;
        }

        public Criteria andLastSyncAtNotEqualTo(Date value) {
            addCriterion("lastSyncAt <>", value, "lastSyncAt");
            return (Criteria) this;
        }

        public Criteria andLastSyncAtGreaterThan(Date value) {
            addCriterion("lastSyncAt >", value, "lastSyncAt");
            return (Criteria) this;
        }

        public Criteria andLastSyncAtGreaterThanOrEqualTo(Date value) {
            addCriterion("lastSyncAt >=", value, "lastSyncAt");
            return (Criteria) this;
        }

        public Criteria andLastSyncAtLessThan(Date value) {
            addCriterion("lastSyncAt <", value, "lastSyncAt");
            return (Criteria) this;
        }

        public Criteria andLastSyncAtLessThanOrEqualTo(Date value) {
            addCriterion("lastSyncAt <=", value, "lastSyncAt");
            return (Criteria) this;
        }

        public Criteria andLastSyncAtIn(List<Date> values) {
            addCriterion("lastSyncAt in", values, "lastSyncAt");
            return (Criteria) this;
        }

        public Criteria andLastSyncAtNotIn(List<Date> values) {
            addCriterion("lastSyncAt not in", values, "lastSyncAt");
            return (Criteria) this;
        }

        public Criteria andLastSyncAtBetween(Date value1, Date value2) {
            addCriterion("lastSyncAt between", value1, value2, "lastSyncAt");
            return (Criteria) this;
        }

        public Criteria andLastSyncAtNotBetween(Date value1, Date value2) {
            addCriterion("lastSyncAt not between", value1, value2, "lastSyncAt");
            return (Criteria) this;
        }

        public Criteria andExpNameIsNull() {
            addCriterion("expName is null");
            return (Criteria) this;
        }

        public Criteria andExpNameIsNotNull() {
            addCriterion("expName is not null");
            return (Criteria) this;
        }

        public Criteria andExpNameEqualTo(String value) {
            addCriterion("expName =", value, "expName");
            return (Criteria) this;
        }

        public Criteria andExpNameNotEqualTo(String value) {
            addCriterion("expName <>", value, "expName");
            return (Criteria) this;
        }

        public Criteria andExpNameGreaterThan(String value) {
            addCriterion("expName >", value, "expName");
            return (Criteria) this;
        }

        public Criteria andExpNameGreaterThanOrEqualTo(String value) {
            addCriterion("expName >=", value, "expName");
            return (Criteria) this;
        }

        public Criteria andExpNameLessThan(String value) {
            addCriterion("expName <", value, "expName");
            return (Criteria) this;
        }

        public Criteria andExpNameLessThanOrEqualTo(String value) {
            addCriterion("expName <=", value, "expName");
            return (Criteria) this;
        }

        public Criteria andExpNameLike(String value) {
            addCriterion("expName like", value, "expName");
            return (Criteria) this;
        }

        public Criteria andExpNameNotLike(String value) {
            addCriterion("expName not like", value, "expName");
            return (Criteria) this;
        }

        public Criteria andExpNameIn(List<String> values) {
            addCriterion("expName in", values, "expName");
            return (Criteria) this;
        }

        public Criteria andExpNameNotIn(List<String> values) {
            addCriterion("expName not in", values, "expName");
            return (Criteria) this;
        }

        public Criteria andExpNameBetween(String value1, String value2) {
            addCriterion("expName between", value1, value2, "expName");
            return (Criteria) this;
        }

        public Criteria andExpNameNotBetween(String value1, String value2) {
            addCriterion("expName not between", value1, value2, "expName");
            return (Criteria) this;
        }

        public Criteria andIdentityCardIsNull() {
            addCriterion("identityCard is null");
            return (Criteria) this;
        }

        public Criteria andIdentityCardIsNotNull() {
            addCriterion("identityCard is not null");
            return (Criteria) this;
        }

        public Criteria andIdentityCardEqualTo(String value) {
            addCriterion("identityCard =", value, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardNotEqualTo(String value) {
            addCriterion("identityCard <>", value, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardGreaterThan(String value) {
            addCriterion("identityCard >", value, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardGreaterThanOrEqualTo(String value) {
            addCriterion("identityCard >=", value, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardLessThan(String value) {
            addCriterion("identityCard <", value, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardLessThanOrEqualTo(String value) {
            addCriterion("identityCard <=", value, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardLike(String value) {
            addCriterion("identityCard like", value, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardNotLike(String value) {
            addCriterion("identityCard not like", value, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardIn(List<String> values) {
            addCriterion("identityCard in", values, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardNotIn(List<String> values) {
            addCriterion("identityCard not in", values, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardBetween(String value1, String value2) {
            addCriterion("identityCard between", value1, value2, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardNotBetween(String value1, String value2) {
            addCriterion("identityCard not between", value1, value2, "identityCard");
            return (Criteria) this;
        }

        public Criteria andSellerNoteIsNull() {
            addCriterion("sellerNote is null");
            return (Criteria) this;
        }

        public Criteria andSellerNoteIsNotNull() {
            addCriterion("sellerNote is not null");
            return (Criteria) this;
        }

        public Criteria andSellerNoteEqualTo(String value) {
            addCriterion("sellerNote =", value, "sellerNote");
            return (Criteria) this;
        }

        public Criteria andSellerNoteNotEqualTo(String value) {
            addCriterion("sellerNote <>", value, "sellerNote");
            return (Criteria) this;
        }

        public Criteria andSellerNoteGreaterThan(String value) {
            addCriterion("sellerNote >", value, "sellerNote");
            return (Criteria) this;
        }

        public Criteria andSellerNoteGreaterThanOrEqualTo(String value) {
            addCriterion("sellerNote >=", value, "sellerNote");
            return (Criteria) this;
        }

        public Criteria andSellerNoteLessThan(String value) {
            addCriterion("sellerNote <", value, "sellerNote");
            return (Criteria) this;
        }

        public Criteria andSellerNoteLessThanOrEqualTo(String value) {
            addCriterion("sellerNote <=", value, "sellerNote");
            return (Criteria) this;
        }

        public Criteria andSellerNoteLike(String value) {
            addCriterion("sellerNote like", value, "sellerNote");
            return (Criteria) this;
        }

        public Criteria andSellerNoteNotLike(String value) {
            addCriterion("sellerNote not like", value, "sellerNote");
            return (Criteria) this;
        }

        public Criteria andSellerNoteIn(List<String> values) {
            addCriterion("sellerNote in", values, "sellerNote");
            return (Criteria) this;
        }

        public Criteria andSellerNoteNotIn(List<String> values) {
            addCriterion("sellerNote not in", values, "sellerNote");
            return (Criteria) this;
        }

        public Criteria andSellerNoteBetween(String value1, String value2) {
            addCriterion("sellerNote between", value1, value2, "sellerNote");
            return (Criteria) this;
        }

        public Criteria andSellerNoteNotBetween(String value1, String value2) {
            addCriterion("sellerNote not between", value1, value2, "sellerNote");
            return (Criteria) this;
        }

        public Criteria andCompleteAtIsNull() {
            addCriterion("completeAt is null");
            return (Criteria) this;
        }

        public Criteria andCompleteAtIsNotNull() {
            addCriterion("completeAt is not null");
            return (Criteria) this;
        }

        public Criteria andCompleteAtEqualTo(Date value) {
            addCriterion("completeAt =", value, "completeAt");
            return (Criteria) this;
        }

        public Criteria andCompleteAtNotEqualTo(Date value) {
            addCriterion("completeAt <>", value, "completeAt");
            return (Criteria) this;
        }

        public Criteria andCompleteAtGreaterThan(Date value) {
            addCriterion("completeAt >", value, "completeAt");
            return (Criteria) this;
        }

        public Criteria andCompleteAtGreaterThanOrEqualTo(Date value) {
            addCriterion("completeAt >=", value, "completeAt");
            return (Criteria) this;
        }

        public Criteria andCompleteAtLessThan(Date value) {
            addCriterion("completeAt <", value, "completeAt");
            return (Criteria) this;
        }

        public Criteria andCompleteAtLessThanOrEqualTo(Date value) {
            addCriterion("completeAt <=", value, "completeAt");
            return (Criteria) this;
        }

        public Criteria andCompleteAtIn(List<Date> values) {
            addCriterion("completeAt in", values, "completeAt");
            return (Criteria) this;
        }

        public Criteria andCompleteAtNotIn(List<Date> values) {
            addCriterion("completeAt not in", values, "completeAt");
            return (Criteria) this;
        }

        public Criteria andCompleteAtBetween(Date value1, Date value2) {
            addCriterion("completeAt between", value1, value2, "completeAt");
            return (Criteria) this;
        }

        public Criteria andCompleteAtNotBetween(Date value1, Date value2) {
            addCriterion("completeAt not between", value1, value2, "completeAt");
            return (Criteria) this;
        }

        public Criteria andWqStatusIsNull() {
            addCriterion("wqStatus is null");
            return (Criteria) this;
        }

        public Criteria andWqStatusIsNotNull() {
            addCriterion("wqStatus is not null");
            return (Criteria) this;
        }

        public Criteria andWqStatusEqualTo(Integer value) {
            addCriterion("wqStatus =", value, "wqStatus");
            return (Criteria) this;
        }

        public Criteria andWqStatusNotEqualTo(Integer value) {
            addCriterion("wqStatus <>", value, "wqStatus");
            return (Criteria) this;
        }

        public Criteria andWqStatusGreaterThan(Integer value) {
            addCriterion("wqStatus >", value, "wqStatus");
            return (Criteria) this;
        }

        public Criteria andWqStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("wqStatus >=", value, "wqStatus");
            return (Criteria) this;
        }

        public Criteria andWqStatusLessThan(Integer value) {
            addCriterion("wqStatus <", value, "wqStatus");
            return (Criteria) this;
        }

        public Criteria andWqStatusLessThanOrEqualTo(Integer value) {
            addCriterion("wqStatus <=", value, "wqStatus");
            return (Criteria) this;
        }

        public Criteria andWqStatusIn(List<Integer> values) {
            addCriterion("wqStatus in", values, "wqStatus");
            return (Criteria) this;
        }

        public Criteria andWqStatusNotIn(List<Integer> values) {
            addCriterion("wqStatus not in", values, "wqStatus");
            return (Criteria) this;
        }

        public Criteria andWqStatusBetween(Integer value1, Integer value2) {
            addCriterion("wqStatus between", value1, value2, "wqStatus");
            return (Criteria) this;
        }

        public Criteria andWqStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("wqStatus not between", value1, value2, "wqStatus");
            return (Criteria) this;
        }

        public Criteria andHoldIsNull() {
            addCriterion("hold is null");
            return (Criteria) this;
        }

        public Criteria andHoldIsNotNull() {
            addCriterion("hold is not null");
            return (Criteria) this;
        }

        public Criteria andHoldEqualTo(Boolean value) {
            addCriterion("hold =", value, "hold");
            return (Criteria) this;
        }

        public Criteria andHoldNotEqualTo(Boolean value) {
            addCriterion("hold <>", value, "hold");
            return (Criteria) this;
        }

        public Criteria andHoldGreaterThan(Boolean value) {
            addCriterion("hold >", value, "hold");
            return (Criteria) this;
        }

        public Criteria andHoldGreaterThanOrEqualTo(Boolean value) {
            addCriterion("hold >=", value, "hold");
            return (Criteria) this;
        }

        public Criteria andHoldLessThan(Boolean value) {
            addCriterion("hold <", value, "hold");
            return (Criteria) this;
        }

        public Criteria andHoldLessThanOrEqualTo(Boolean value) {
            addCriterion("hold <=", value, "hold");
            return (Criteria) this;
        }

        public Criteria andHoldIn(List<Boolean> values) {
            addCriterion("hold in", values, "hold");
            return (Criteria) this;
        }

        public Criteria andHoldNotIn(List<Boolean> values) {
            addCriterion("hold not in", values, "hold");
            return (Criteria) this;
        }

        public Criteria andHoldBetween(Boolean value1, Boolean value2) {
            addCriterion("hold between", value1, value2, "hold");
            return (Criteria) this;
        }

        public Criteria andHoldNotBetween(Boolean value1, Boolean value2) {
            addCriterion("hold not between", value1, value2, "hold");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ym_order
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ym_order
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}