package com.yannyao.demo.mybatis_generator.domain;

import java.math.BigDecimal;
import java.util.Date;

public class YmOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_order.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_order.tid
     *
     * @mbggenerated
     */
    private Long tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_order.userId
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_order.addressId
     *
     * @mbggenerated
     */
    private Long addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_order.shopId
     *
     * @mbggenerated
     */
    private Long shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_order.activityType
     *
     * @mbggenerated
     */
    private Integer activityType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_order.activityId
     *
     * @mbggenerated
     */
    private Long activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_order.paymentRecordId
     *
     * @mbggenerated
     */
    private Long paymentRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_order.orderNo
     *
     * @mbggenerated
     */
    private Long orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_order.shipNo
     *
     * @mbggenerated
     */
    private String shipNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_order.orderTotalPrice
     *
     * @mbggenerated
     */
    private BigDecimal orderTotalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_order.orderRealPrice
     *
     * @mbggenerated
     */
    private BigDecimal orderRealPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_order.activityDiscount
     *
     * @mbggenerated
     */
    private BigDecimal activityDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_order.couponDiscount
     *
     * @mbggenerated
     */
    private BigDecimal couponDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_order.fare
     *
     * @mbggenerated
     */
    private BigDecimal fare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_order.orderStatus
     *
     * @mbggenerated
     */
    private String orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_order.shipStatus
     *
     * @mbggenerated
     */
    private String shipStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_order.payAt
     *
     * @mbggenerated
     */
    private Date payAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_order.sendAt
     *
     * @mbggenerated
     */
    private Date sendAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_order.createAt
     *
     * @mbggenerated
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_order.updateAt
     *
     * @mbggenerated
     */
    private Date updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_order.archive
     *
     * @mbggenerated
     */
    private Boolean archive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_order.receiveAt
     *
     * @mbggenerated
     */
    private Date receiveAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_order.extendReceive
     *
     * @mbggenerated
     */
    private Boolean extendReceive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_order.fx
     *
     * @mbggenerated
     */
    private Boolean fx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_order.platformId
     *
     * @mbggenerated
     */
    private Long platformId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_order.pushERP
     *
     * @mbggenerated
     */
    private Boolean pushERP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_order.pushCancelERP
     *
     * @mbggenerated
     */
    private Boolean pushCancelERP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_order.lastSyncAt
     *
     * @mbggenerated
     */
    private Date lastSyncAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_order.expName
     *
     * @mbggenerated
     */
    private String expName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_order.identityCard
     *
     * @mbggenerated
     */
    private String identityCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_order.sellerNote
     *
     * @mbggenerated
     */
    private String sellerNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_order.completeAt
     *
     * @mbggenerated
     */
    private Date completeAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_order.wqStatus
     *
     * @mbggenerated
     */
    private Integer wqStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_order.hold
     *
     * @mbggenerated
     */
    private Boolean hold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_order.productSubjects
     *
     * @mbggenerated
     */
    private String productSubjects;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_order.id
     *
     * @return the value of ym_order.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_order.id
     *
     * @param id the value for ym_order.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_order.tid
     *
     * @return the value of ym_order.tid
     *
     * @mbggenerated
     */
    public Long getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_order.tid
     *
     * @param tid the value for ym_order.tid
     *
     * @mbggenerated
     */
    public void setTid(Long tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_order.userId
     *
     * @return the value of ym_order.userId
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_order.userId
     *
     * @param userId the value for ym_order.userId
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_order.addressId
     *
     * @return the value of ym_order.addressId
     *
     * @mbggenerated
     */
    public Long getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_order.addressId
     *
     * @param addressId the value for ym_order.addressId
     *
     * @mbggenerated
     */
    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_order.shopId
     *
     * @return the value of ym_order.shopId
     *
     * @mbggenerated
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_order.shopId
     *
     * @param shopId the value for ym_order.shopId
     *
     * @mbggenerated
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_order.activityType
     *
     * @return the value of ym_order.activityType
     *
     * @mbggenerated
     */
    public Integer getActivityType() {
        return activityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_order.activityType
     *
     * @param activityType the value for ym_order.activityType
     *
     * @mbggenerated
     */
    public void setActivityType(Integer activityType) {
        this.activityType = activityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_order.activityId
     *
     * @return the value of ym_order.activityId
     *
     * @mbggenerated
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_order.activityId
     *
     * @param activityId the value for ym_order.activityId
     *
     * @mbggenerated
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_order.paymentRecordId
     *
     * @return the value of ym_order.paymentRecordId
     *
     * @mbggenerated
     */
    public Long getPaymentRecordId() {
        return paymentRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_order.paymentRecordId
     *
     * @param paymentRecordId the value for ym_order.paymentRecordId
     *
     * @mbggenerated
     */
    public void setPaymentRecordId(Long paymentRecordId) {
        this.paymentRecordId = paymentRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_order.orderNo
     *
     * @return the value of ym_order.orderNo
     *
     * @mbggenerated
     */
    public Long getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_order.orderNo
     *
     * @param orderNo the value for ym_order.orderNo
     *
     * @mbggenerated
     */
    public void setOrderNo(Long orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_order.shipNo
     *
     * @return the value of ym_order.shipNo
     *
     * @mbggenerated
     */
    public String getShipNo() {
        return shipNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_order.shipNo
     *
     * @param shipNo the value for ym_order.shipNo
     *
     * @mbggenerated
     */
    public void setShipNo(String shipNo) {
        this.shipNo = shipNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_order.orderTotalPrice
     *
     * @return the value of ym_order.orderTotalPrice
     *
     * @mbggenerated
     */
    public BigDecimal getOrderTotalPrice() {
        return orderTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_order.orderTotalPrice
     *
     * @param orderTotalPrice the value for ym_order.orderTotalPrice
     *
     * @mbggenerated
     */
    public void setOrderTotalPrice(BigDecimal orderTotalPrice) {
        this.orderTotalPrice = orderTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_order.orderRealPrice
     *
     * @return the value of ym_order.orderRealPrice
     *
     * @mbggenerated
     */
    public BigDecimal getOrderRealPrice() {
        return orderRealPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_order.orderRealPrice
     *
     * @param orderRealPrice the value for ym_order.orderRealPrice
     *
     * @mbggenerated
     */
    public void setOrderRealPrice(BigDecimal orderRealPrice) {
        this.orderRealPrice = orderRealPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_order.activityDiscount
     *
     * @return the value of ym_order.activityDiscount
     *
     * @mbggenerated
     */
    public BigDecimal getActivityDiscount() {
        return activityDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_order.activityDiscount
     *
     * @param activityDiscount the value for ym_order.activityDiscount
     *
     * @mbggenerated
     */
    public void setActivityDiscount(BigDecimal activityDiscount) {
        this.activityDiscount = activityDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_order.couponDiscount
     *
     * @return the value of ym_order.couponDiscount
     *
     * @mbggenerated
     */
    public BigDecimal getCouponDiscount() {
        return couponDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_order.couponDiscount
     *
     * @param couponDiscount the value for ym_order.couponDiscount
     *
     * @mbggenerated
     */
    public void setCouponDiscount(BigDecimal couponDiscount) {
        this.couponDiscount = couponDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_order.fare
     *
     * @return the value of ym_order.fare
     *
     * @mbggenerated
     */
    public BigDecimal getFare() {
        return fare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_order.fare
     *
     * @param fare the value for ym_order.fare
     *
     * @mbggenerated
     */
    public void setFare(BigDecimal fare) {
        this.fare = fare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_order.orderStatus
     *
     * @return the value of ym_order.orderStatus
     *
     * @mbggenerated
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_order.orderStatus
     *
     * @param orderStatus the value for ym_order.orderStatus
     *
     * @mbggenerated
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_order.shipStatus
     *
     * @return the value of ym_order.shipStatus
     *
     * @mbggenerated
     */
    public String getShipStatus() {
        return shipStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_order.shipStatus
     *
     * @param shipStatus the value for ym_order.shipStatus
     *
     * @mbggenerated
     */
    public void setShipStatus(String shipStatus) {
        this.shipStatus = shipStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_order.payAt
     *
     * @return the value of ym_order.payAt
     *
     * @mbggenerated
     */
    public Date getPayAt() {
        return payAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_order.payAt
     *
     * @param payAt the value for ym_order.payAt
     *
     * @mbggenerated
     */
    public void setPayAt(Date payAt) {
        this.payAt = payAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_order.sendAt
     *
     * @return the value of ym_order.sendAt
     *
     * @mbggenerated
     */
    public Date getSendAt() {
        return sendAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_order.sendAt
     *
     * @param sendAt the value for ym_order.sendAt
     *
     * @mbggenerated
     */
    public void setSendAt(Date sendAt) {
        this.sendAt = sendAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_order.createAt
     *
     * @return the value of ym_order.createAt
     *
     * @mbggenerated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_order.createAt
     *
     * @param createAt the value for ym_order.createAt
     *
     * @mbggenerated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_order.updateAt
     *
     * @return the value of ym_order.updateAt
     *
     * @mbggenerated
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_order.updateAt
     *
     * @param updateAt the value for ym_order.updateAt
     *
     * @mbggenerated
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_order.archive
     *
     * @return the value of ym_order.archive
     *
     * @mbggenerated
     */
    public Boolean getArchive() {
        return archive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_order.archive
     *
     * @param archive the value for ym_order.archive
     *
     * @mbggenerated
     */
    public void setArchive(Boolean archive) {
        this.archive = archive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_order.receiveAt
     *
     * @return the value of ym_order.receiveAt
     *
     * @mbggenerated
     */
    public Date getReceiveAt() {
        return receiveAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_order.receiveAt
     *
     * @param receiveAt the value for ym_order.receiveAt
     *
     * @mbggenerated
     */
    public void setReceiveAt(Date receiveAt) {
        this.receiveAt = receiveAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_order.extendReceive
     *
     * @return the value of ym_order.extendReceive
     *
     * @mbggenerated
     */
    public Boolean getExtendReceive() {
        return extendReceive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_order.extendReceive
     *
     * @param extendReceive the value for ym_order.extendReceive
     *
     * @mbggenerated
     */
    public void setExtendReceive(Boolean extendReceive) {
        this.extendReceive = extendReceive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_order.fx
     *
     * @return the value of ym_order.fx
     *
     * @mbggenerated
     */
    public Boolean getFx() {
        return fx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_order.fx
     *
     * @param fx the value for ym_order.fx
     *
     * @mbggenerated
     */
    public void setFx(Boolean fx) {
        this.fx = fx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_order.platformId
     *
     * @return the value of ym_order.platformId
     *
     * @mbggenerated
     */
    public Long getPlatformId() {
        return platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_order.platformId
     *
     * @param platformId the value for ym_order.platformId
     *
     * @mbggenerated
     */
    public void setPlatformId(Long platformId) {
        this.platformId = platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_order.pushERP
     *
     * @return the value of ym_order.pushERP
     *
     * @mbggenerated
     */
    public Boolean getPushERP() {
        return pushERP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_order.pushERP
     *
     * @param pushERP the value for ym_order.pushERP
     *
     * @mbggenerated
     */
    public void setPushERP(Boolean pushERP) {
        this.pushERP = pushERP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_order.pushCancelERP
     *
     * @return the value of ym_order.pushCancelERP
     *
     * @mbggenerated
     */
    public Boolean getPushCancelERP() {
        return pushCancelERP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_order.pushCancelERP
     *
     * @param pushCancelERP the value for ym_order.pushCancelERP
     *
     * @mbggenerated
     */
    public void setPushCancelERP(Boolean pushCancelERP) {
        this.pushCancelERP = pushCancelERP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_order.lastSyncAt
     *
     * @return the value of ym_order.lastSyncAt
     *
     * @mbggenerated
     */
    public Date getLastSyncAt() {
        return lastSyncAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_order.lastSyncAt
     *
     * @param lastSyncAt the value for ym_order.lastSyncAt
     *
     * @mbggenerated
     */
    public void setLastSyncAt(Date lastSyncAt) {
        this.lastSyncAt = lastSyncAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_order.expName
     *
     * @return the value of ym_order.expName
     *
     * @mbggenerated
     */
    public String getExpName() {
        return expName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_order.expName
     *
     * @param expName the value for ym_order.expName
     *
     * @mbggenerated
     */
    public void setExpName(String expName) {
        this.expName = expName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_order.identityCard
     *
     * @return the value of ym_order.identityCard
     *
     * @mbggenerated
     */
    public String getIdentityCard() {
        return identityCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_order.identityCard
     *
     * @param identityCard the value for ym_order.identityCard
     *
     * @mbggenerated
     */
    public void setIdentityCard(String identityCard) {
        this.identityCard = identityCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_order.sellerNote
     *
     * @return the value of ym_order.sellerNote
     *
     * @mbggenerated
     */
    public String getSellerNote() {
        return sellerNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_order.sellerNote
     *
     * @param sellerNote the value for ym_order.sellerNote
     *
     * @mbggenerated
     */
    public void setSellerNote(String sellerNote) {
        this.sellerNote = sellerNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_order.completeAt
     *
     * @return the value of ym_order.completeAt
     *
     * @mbggenerated
     */
    public Date getCompleteAt() {
        return completeAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_order.completeAt
     *
     * @param completeAt the value for ym_order.completeAt
     *
     * @mbggenerated
     */
    public void setCompleteAt(Date completeAt) {
        this.completeAt = completeAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_order.wqStatus
     *
     * @return the value of ym_order.wqStatus
     *
     * @mbggenerated
     */
    public Integer getWqStatus() {
        return wqStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_order.wqStatus
     *
     * @param wqStatus the value for ym_order.wqStatus
     *
     * @mbggenerated
     */
    public void setWqStatus(Integer wqStatus) {
        this.wqStatus = wqStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_order.hold
     *
     * @return the value of ym_order.hold
     *
     * @mbggenerated
     */
    public Boolean getHold() {
        return hold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_order.hold
     *
     * @param hold the value for ym_order.hold
     *
     * @mbggenerated
     */
    public void setHold(Boolean hold) {
        this.hold = hold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_order.productSubjects
     *
     * @return the value of ym_order.productSubjects
     *
     * @mbggenerated
     */
    public String getProductSubjects() {
        return productSubjects;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_order.productSubjects
     *
     * @param productSubjects the value for ym_order.productSubjects
     *
     * @mbggenerated
     */
    public void setProductSubjects(String productSubjects) {
        this.productSubjects = productSubjects;
    }
}