package com.yannyao.demo.mybatis_generator.domain;

import java.util.Date;

public class YmShip {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_ship.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_ship.orderId
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_ship.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ym_ship.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_ship.id
     *
     * @return the value of ym_ship.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_ship.id
     *
     * @param id the value for ym_ship.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_ship.orderId
     *
     * @return the value of ym_ship.orderId
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_ship.orderId
     *
     * @param orderId the value for ym_ship.orderId
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_ship.time
     *
     * @return the value of ym_ship.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_ship.time
     *
     * @param time the value for ym_ship.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ym_ship.status
     *
     * @return the value of ym_ship.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ym_ship.status
     *
     * @param status the value for ym_ship.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }
}